### PR TITLE
Add scene selection to the rest of the object types

### LINKED ISSUE #391: Implement object selection in scene
See hover implementation here: 
* https://github.com/ccnmtl/astro-simulations/blob/master/sun-motion-simulator/src/CelestialSphere.jsx#L926
* https://discourse.threejs.org/t/finding-nearest-vertex-of-a-mesh-to-mouse-cursor/4167/1

### PR DESCRIPTION
**Pull request by nikolas**
Closes #391

### CODE REVIEW

**Comment by Evan-CTL** [comment]
There is an issue with the `Level` selection. The select only seems to work within a 1 unit sphere centered on the origin. An space outside of that selection is inactive, you can tell because the cursor doesn't change to the little hand.

**Comment by nikolas** [comment]
Okay - I'll take a look. I tested all these, but not extensively.

**Comment by nikolas** [comment]
Ah okay - I def see what you're talking about. I'll fix on this branch.

**Comment by nikolas** [comment]
Weird - now I can't reproduce the problem.. I did a rebase, maybe other changes fixed it?

Anyways, I'll keep an eye out for it.

**Comment by Evan-CTL** [comment]
Wait, didn't you fix it? I checked it out after you pushed the change. It looked good so I merged it.

**Pull request merged**
