### PR TITLE
Display three.js outline on selected object

### PR DESCRIPTION
**Pull request by nikolas**
Following this example here:
https://threejs.org/examples/webgl_postprocessing_outline.html

### CODE REVIEW

**Comment by ndittren** [comment]
@nikolas It works good for me except for the "Solid Region" object. It is not clickable/doesn't display an outline.

**Comment by nikolas** [comment]
Yeah, the Solid object isn't clickable yet because of how it's implemented - that's a known issue and we'll handle it separately.. I just made an issue for this here: https://github.com/ccnmtl/3demos/issues/525

**Comment by drewyoungren** [comment]
Folks, we did not finalize how we wanted selection of objects indicated. It was agreed there should be some visual queue, but this is the sort of thing that needs more discussion before being put on the production side. This is a good thing to implementd and test on a branch of course, but not to merge unilaterally.

**Comment by Evan-CTL** [comment]
Back from my break, sounds like there's been a misunderstanding. Let's pin this down this Wednesday when we're all together.

**Pull request merged**
