### PR TITLE
On poll receive, display poll

### PR DESCRIPTION
**Pull request by nikolas**
The poll view should be visible when the user receives a poll, whatever state the application is in.

### CODE REVIEW

**Comment by Evan-CTL** [comment]
Polls don't pop up if you are in `Info`. `currentMode` needs to be switched to 'session' when the student receives the poll.

**Comment by nikolas** [comment]
Good catch, i'll make that adjustment.

**Comment by Evan-CTL** [comment]
It's less responsive now. Now the poll broadcast doesn't work for students in Info or the Object List.

**Comment by nikolas** [comment]
Is this a problem with your dev environment? I can't reproduce the problem. Try restarting the django server..

**Comment by Evan-CTL** [comment]
Same issue. I tried restarting redis and then nginx, then I tried `make clean`, `npm install`, `make runserver`, `npm run dev`. It still doesn't pop to the poll if students are in the Object List. I'm not sure what the difference is between our builds that could be causing the issue. Did you change your local settings recently?

**Pull request merged**
