### PR TITLE
Introduce resizable Panel

### PR DESCRIPTION
**Pull request by nikolas**
This major refactor puts all the form components and text parts of the app inside a new Panel component.

Next steps:
* Add button to toggle hide/show state for Panel
* Possibly separate Object List from "content" area, each in their own boxes

### CODE REVIEW

**Comment by drewyoungren** [comment]
This is definitely an improvement in the right direction. Certainly tight is the way to go. 

I do have a hangup I can't let go despite it not really making sense. I need to feel the canvas filling up the whole viewable window. As soon as it feels like picture-in-picture I feel weirdly claustrophobic. Could we try even a slight bit of transparency to the panels so some movement behind can be detected?

**Comment by nikolas** [comment]
Yeah, so I initially put this together where the panel and scene were side-by-side, with the scene not actually overlapping the panel, so it felt more like a traditional application like Blender or Photoshop. But then I saw all the empty space within the Panel, and figured the scene might as well take up the whole area, even if the panel overlaps it.

I'll adjust the transparency here to see if I can get it to feel better like this.

**Comment by nikolas** [comment]
@drewyoungren so we do rebases rather than merges to keep branches up to date - the merge commit you added here makes it a bit difficult to resolve these merge conflicts since `main` was just updated. I'm resolving now though, and it should be taken care of soon.

**Comment by nikolas** [comment]
I see you were actually adding a new commit with new changes here too, though. Anyways, I hope I didn't lose any of your changes in my rebase here.

**Comment by drewyoungren** [comment]
Ah. I was wondering why I couldn't pull the panel branch. I should have
`git config pull.rebase=true` yeah? I was told this is a bad idea generally
but I am not sure by whom or why.

Drew C Youngren
Lecturer in Discipline
Applied Physics & Applied Mathematics
Columbia University

**Comment by nikolas** [comment]
Ah - I'm not familiar with that config option. Sometimes I'll do `git pull --rebase`, but in general, to pull a rebased branch I delete the local copy of the branch, and then get the new remote one. That would look like this:
```
# switch to main branch
git checkout main
# get new changes (`git fetch origin` would essential do the same thing here)
git pull
# delete local copy of branch
git branch -D my-branch
# switch to new branch
git checkout my-branch
```

In practice, we don't tend to have to do this process so often as we don't collaborate on the same branch together that much, as that can get messy. We'll generally just work off the main branch.

**Comment by drewyoungren** [comment]
No I didn't intend to make any changes was just trying to catch up to the
latest commit and used the wrong strategy. I'm sorry for making extra work.

Drew C Youngren
Lecturer in Discipline
Applied Physics & Applied Mathematics
Columbia University

**Comment by nikolas** [comment]
No worries, it's all good. Worst case scenario, I always have my local copy of the branch's changes and can just revert to those if needed.

**Pull request merged**
