### PR TITLE
Introduce resizable Panel

### PR DESCRIPTION
**Pull request by nikolas**
This major refactor puts all the form components and text parts of the app inside a new Panel component.

Next steps:
* Add button to toggle hide/show state for Panel

### CODE REVIEW

**Comment by drewyoungren** [comment]
We can't have the listeners running when editing the input fields. 
shortcuts

**Comment by nikolas** [comment]
Alright - worth another round of QA here, but no rush to merge obviously.

I couldn't find a nice property to use within the [keydown event](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) to determine whether or not this keystroke happened within an input, but this method of doing it proposed on stackoverflow seems to work: https://stackoverflow.com/a/58404018/173630

**Comment by drewyoungren** [comment]
Just put an unintended commit up while transferring computers. Thought I
was on a new branch. Feel free to quash it.


Drew C Youngren
Lecturer in Discipline
Applied Physics & Applied Mathematics
Columbia University

**Comment by nikolas** [comment]
haha got it, no problem.

**Comment by nikolas** [comment]
This branch is ready for another review. Obviously there is a lot of fine-tuning regarding how exactly everything behaves here which we'll discuss tomorrow, but the general direction of how we're laying everything out should be what we discussed last Wednesday.

**Pull request merged**
