### PR TITLE
Arclength and then some

### PR DESCRIPTION
**Pull request by drewyoungren**
Includes commits for #627. Uses the `title` property to import existing curves into story examples. 
Also restores old objects on close of story (not done with tab switch now) which has to be done via select story menu. Need to think about what behavior is best.

Includes several improvements to flash behavior:
  - auto select when using the "Add Object+" menu but not when added by other means
  - Prevents bug when flashed too quickly consecutively. Disables while first runs. 
  - Does not flash on parameter changes.

### CODE REVIEW

**Comment by Evan-CTL** [comment]
Are you still working through this or is it open for review?

**Comment by drewyoungren** [comment]
> Are you still working through this or is it open for review?

Review away.

**Comment by Evan-CTL** [comment]
Looks good for the most part.

Linearization needs to be updated. There is a formatting issue with one of the LaTex segments, and the hide button is still there.

**Comment by drewyoungren** [comment]
See #647

**Pull request closed without merging**
