### PR TITLE
Track host presence

### PR DESCRIPTION
**Pull request by Evan-CTL**
It immediately updates when the host connects but when the host disconnects, while the host presence is marked as False, it doesn't update the user page. You can't see the change unless the user refreshes the page.

### CODE REVIEW

**Comment by Evan-CTL** [comment]
I rearranged the sequencing for the active user count as well and it appears to be snappier.

**Comment by nikolas** [comment]
I think updating the scene state when any client connects or disconnects is unnecessary, and opens us up to possible issues in this area. It doesn't merit what this feature provides. The 'host presence' flag isn't really solving a use case that the faculty or students have requested - but in general, the intention to make clear the state of the scene to make any bugs more obvious is good.

**Comment by Evan-CTL** [comment]
So you're saying put this on hold?

**Comment by nikolas** [comment]
Yeah - this just, isn't really necessary, so I'm closing for now.

**Pull request closed without merging**
