### PR TITLE
Change "Broadcast results" button to toggle

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by Evan-CTL** [comment]
The toggle is a step in the right direction, but there is no live update on the viewer's side. Results are not shown or updated to the user when submitting a response, editing an old response or after entering the room and Broadcast Results is on with results to show. Also nothing appears until there is at least one response and it does not update after the first response populates. This means that the presenter has to toggle `Broadcast Results` off, then on again to display the new results. Actively more work than the previous button implementation.

Could we run the `broadcastPollResults` function at the end of the `handleSocketMessage` function in the condition where it checks for pollResponse?

Or maybe change the `&& isHost` bit on line 493 to `&& (isHost || broadcastResults)`? That might provide a live update, though it would require some more modification to play catch up when `Broadcast Results` isn't active. Maybe the toggle function sets broadcastResults to True then queries the user to broadcast the results. Same for people entering the room?

**Comment by nikolas** [comment]
Hmmm, good point - yeah, looks like the new poll results aren't getting propagated out to the students' clients. That boolean statement you mentioned will need some adjustment, and possibly a few other things, from my testing.. I'll take another look here.

**Comment by Evan-CTL** [comment]
Asking about the expected behavior. Is the toggle just to show/hide the last posted results? Because the results shown are only those that appeared before `Broadcast Results` is toggled on, and it doesn't update until the next time that `Broadcast Poll` is toggled on. If that's the case then would it be more clear to call the toggle `Show / Hide Results`?

**Comment by Evan-CTL** [comment]
Understood. From what you said I don't think the name has to change. I was just getting confused because it wasn't updating on the student side.

**Comment by nikolas** [comment]
Alright, the functionality here is ready for another review.

The UI here can be unified with the new Restrict Updates button - these are both essentially toggles and we can decide on either the button or bootstrap's toggle element for both. We can handle that separately though, and just focus on the functionality to get this merged.
Screenshot_2023-05-31_16-37-20

**Comment by Evan-CTL** [comment]
Merging, but keep in mind that the poll does not show for students entering the room after the toggle is turned on. It need to be turned off, then on again.

**Comment by nikolas** [comment]
Right... I suppose the `showPollResults` boolean would have to be part of the room's state in order for that to work, I was just trying to keep things simple as possible here. We can add that, though.

**Pull request merged**
